[package]
name = "glicol-cli"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.1.8", features = ["derive"] }
glicol = "0.13.1"
cpal =  "0.15.0"
chrono = "0.4.23"

# jack = { version = "0.11", optional = true }
# [features]
# default = []
# jack = []